is-research-different.pdf: is-research-different.bbl
	xelatex is-research-different.tex

is-research-different.bbl:
	xelatex is-research-different.tex
	biber is-research-different.bcf
	xelatex is-research-different.tex
